name: Attendance Logger Bot

on:
  push:
    branches:
      - master
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get comment timestamp
        id: get_timestamp
        env:
          RAW_TIMESTAMP: ${{ github.event.comment.created_at }}
        run: |
          epoch_seconds=$(date -d "$RAW_TIMESTAMP" +%s)
          ist_seconds=$((epoch_seconds + 19800))
          ist_time=$(date -u -d "@$ist_seconds" "+%H:%M")
          final_date=$(date -d "$RAW_TIMESTAMP" "+%d-%m-%Y")
          echo "timestamp=$ist_time" >> $GITHUB_OUTPUT
          echo "final_date=s$final_date" >> $GITHUB_OUTPUT

      - name: Check if comment contains /login or /logout
        id: check_command
        env:
          COMMENT_BODY: ${{ github.event.comment.body || '' }}
          FULL_NAME: ${{ github.event.comment.user.login }}
        run: |
          full_name="$FULL_NAME"
          first_name="${full_name%%-*}"
          echo "first_name=$first_name" >> $GITHUB_OUTPUT
          comment="$COMMENT_BODY"
          if [[ "$comment" == *"/login"* ]]; then
            echo "command=login" >> $GITHUB_OUTPUT
          elif [[ "$comment" == *"/logout"* ]]; then
            echo "command=logout" >> $GITHUB_OUTPUT
          else
            echo "command=none" >> $GITHUB_OUTPUT
          fi

      - name: Post login comment
        if: steps.check_command.outputs.command == 'login'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Good Morning @${{ steps.check_command.outputs.first_name }}! :D Your login has been recorded at ${{ steps.get_timestamp.outputs.timestamp }} 

      - name: Post logout comment
        if: steps.check_command.outputs.command == 'logout'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            See You Tomorrow, @${{ steps.check_command.outputs.first_name }}! ;) Your logout has been recorded at ${{ steps.get_timestamp.outputs.timestamp }}. 

      - name: write to attendance.md
        if: steps.check_command.outputs.command == 'login'
        run: |
          cat >> test/attendance.md <<EOF
          | ${{ github.event.comment.user.login }} | ${{ steps.get_timestamp.outputs.final_date }} | ${{ steps.get_timestamp.outputs.timestamp }} |   |  |
          EOF

      - name: write to attendance.md for logout
        if: steps.check_command.outputs.command == 'logout'
        run: |
          cat >> test/attendance.md <<EOF
          | ${{ github.event.comment.user.login }} |  |  |  |  ${{ steps.get_timestamp.outputs.timestamp }} |
          EOF
